---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: kafka-placement
  namespace: kafka
  labels:
    app: kafka
spec:
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
  clusterReplicas: 1
  schedulerName: "ramen"
