---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/github-branch: main
    apps.open-cluster-management.io/github-path: install/amq_install
  labels:
    app: kafka-sample
  name: kafka-sub
spec:
    channel: ramen-busybox/ramen-gitops
    placement:
      placementRef:
        kind: PlacementRule
        name: kafka-placement
